import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import styled from 'styled-components';

const Test = styled.div`
  width: 100vw;
  height: 100vh;
  background-color: #000;
  color: 000;
`;

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Test>
        asdsadsad
      </Test>
    </div>
  )
}
